### ISSUE TITLE
Values not clear

### ISSUE THREAD

**Issue by Ohwelt** [dirkjanfaber/victron-vrm-api#2]
Hi Dirk,
Could you please give some explanations for the different values for example:

vrm_solar_irradiance_fc: 170.16666666666666
vrm_pv_charger_yield_fc: 8155.842231439
vrm_solar_irradiance:: false
vrm_pv_inverter_yield_fc: false

Also the meaning of 1 hour, 2 hours, 1 day.
Thanks!

**Comment by dirkjanfaber** [comment]
I am not the one creating the actual API side of things. So your guess on the values is as good (or bad) as mine. 
As the info on https://vrm-api-docs.victronenergy.com/#/operations/installations/idSite/stats is sparse, I usually trial and error and compare to the VRM site to get the right data. 
For the node, I've tried to match the terming as much as possible with the documentation of the actual API. So that 1 hour, 2 hours and 1 day is the interval.
